name: Nim CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion:
          - binary:stable
        os:
          - ubuntu-latest
          - macOS-13
          - windows-latest
    steps:
    - uses: actions/checkout@v1

    - uses: iffy/install-nim@v5
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compile Nim file
      run: nim c -d:release -o:Doin Doin.nim

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: File-${{ matrix.os }}
        path: File*
